# Generated by Django 3.1.2 on 2023-11-08 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotus', '0005_groupapp_grouppage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouppage',
            name='group',
        ),
        migrations.RemoveField(
            model_name='grouppage',
            name='page',
        ),
        migrations.DeleteModel(
            name='GroupApp',
        ),
        migrations.DeleteModel(
            name='GroupPage',
        ),
    ]
