# Generated by Django 3.1.2 on 2023-11-08 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotus', '0007_groupapp_grouppage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagegroup',
            name='group',
        ),
        migrations.RemoveField(
            model_name='pagegroup',
            name='page',
        ),
        migrations.DeleteModel(
            name='AppGroup',
        ),
        migrations.DeleteModel(
            name='PageGroup',
        ),
    ]
