# Generated by Django 3.1.2 on 2023-11-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotus', '0008_auto_20231108_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergroup',
            name='is_enabled',
        ),
        migrations.AddField(
            model_name='page',
            name='is_action_button',
            field=models.BooleanField(default=False),
        ),
    ]
