# Generated by Django 3.1.2 on 2023-11-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotus', '0009_auto_20231109_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='url',
            field=models.CharField(blank=True, max_length=225, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='page',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='page',
            name='url',
            field=models.CharField(blank=True, max_length=225, null=True, unique=True),
        ),
    ]
