# Generated by Django 3.1.2 on 2023-11-11 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotus', '0010_auto_20231109_2326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='url',
            new_name='path',
        ),
        migrations.RemoveField(
            model_name='page',
            name='slug',
        ),
    ]
