# Generated by Django 3.1.2 on 2023-11-29 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotus', '0013_auto_20231114_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='as_app_select',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='app',
            name='sequence',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
