# Generated by Django 3.1.2 on 2023-11-29 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotus', '0014_auto_20231129_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='icon_class',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='app',
            name='user_list',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
