# Generated by Django 3.1.2 on 2023-11-29 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotus', '0015_auto_20231129_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='url',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
