# Generated by Django 3.1.2 on 2023-12-04 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lotus', '0016_auto_20231129_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyrelationshiptype',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lotus_family_relationship_type_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='familyrelationshiptype',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lotus_family_relationship_type_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EducationalLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225, unique=True)),
                ('description', models.CharField(blank=True, max_length=225, null=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lotus_educational_level_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lotus_educational_level_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
