# Generated by Django 3.1.2 on 2023-12-04 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotus', '0017_auto_20231205_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
