# Generated by Django 3.1.2 on 2024-01-02 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotus', '0021_auto_20231215_0647'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='init_log',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_logged',
            field=models.BooleanField(default=False),
        ),
    ]
