# Generated by Django 3.1.2 on 2024-01-04 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotus', '0022_auto_20240102_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='init_log',
        ),
    ]
