# Generated by Django 3.1.2 on 2024-01-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotus', '0022_auto_20240102_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='is_enabled',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
