# Generated by Django 3.1.2 on 2024-01-03 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotus', '0023_auto_20240102_2250'),
        ('lotus', '0022_auto_20240103_0714'),
    ]

    operations = [
    ]
