# Generated by Django 3.1.2 on 2024-01-04 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotus', '0023_remove_user_init_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='init_log',
            field=models.BooleanField(default=True),
        ),
    ]
